services:
  discord-bot-v2:
    build: .
    container_name: discord-bot-v2
    environment:
      - NODE_ENV: ${NODE_ENV}
      - TOKEN: ${TOKEN}
      - CLIENT_ID: ${CLIENT_ID}
      - BEARER: ${BEARER}
      - BASE_URL_DATA_API: ${BASE_URL_DATA_API}
      - IMAGE_URL: ${IMAGE_URL}
      - BOT_VERSION: ${BOT_VERSION}
    restart: unless-stopped
    networks:
      - web

    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

networks:
  web:
    external: true
