services:
  discord-bot-v2:
    build: .
    container_name: discord-bot-v2
    environment:
      NODE_ENV: ${NODE_ENV}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      ONLINE_SERVER_BEARER_TOKEN: ${ONLINE_SERVER_BEARER_TOKEN}
      ONLINE_SERVER_API_URL: ${ONLINE_SERVER_API_URL}
      DATA_API_BASE_URL: ${DATA_API_BASE_URL}
      POKEMON_IMAGE_BASE_URL: ${POKEMON_IMAGE_BASE_URL}
      DISCORD_BOT_NAME: ${DISCORD_BOT_NAME}
      DISCORD_BOT_VERSION: ${DISCORD_BOT_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - web

    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

networks:
  web:
    external: true
